version: '3.7'

services:
  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
#    command: gunicorn photobook.wsgi:application -w 5 --bind 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - 8000:8000
    links:
      - redis:redis
    volumes:
      - ./web/db.sqlite3:/usr/src/app/db.sqlite3
      - ./log/file.log:/usr/src/app/file.log
    depends_on:
      - redis

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./log/nginx_access.log:/var/log/nginx/access.log
      - ./log/nginx_error.log:/var/log/nginx/error.log
    ports:
      - 80:80
    depends_on:
      - web

  celery:
    build: ./web
    command: celery -A photobook worker -l INFO
    restart: always
    volumes:
      - ./web/db.sqlite3:/usr/src/app/db.sqlite3
    depends_on:
      - web
      - redis

  flower:
    build: ./web
    command: flower -A photobook --port=1338
    restart: always
    ports:
      - 81:1338
    depends_on:
      - celery

  redis:
    build: ./redis
    restart: always
    expose:
      - 6379
