# Generated by Django 3.1.6 on 2021-02-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210218_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filename',
        ),
        migrations.AddField(
            model_name='photo',
            name='original_file',
            field=models.ImageField(default='no-image.png', upload_to='original'),
        ),
        migrations.AddField(
            model_name='photo',
            name='small_file',
            field=models.ImageField(default='no-image.png', upload_to='small'),
        ),
        migrations.AddField(
            model_name='photo',
            name='webm_file',
            field=models.ImageField(default='no-image.png', upload_to='webm'),
        ),
    ]
