# Generated by Django 3.1.6 on 2021-02-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210219_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='small_file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='webm_file',
        ),
    ]
