# Generated by Django 3.1.6 on 2021-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210220_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='webm_file',
        ),
        migrations.AddField(
            model_name='photo',
            name='webp_file',
            field=models.ImageField(default='no-image.png', upload_to='webp'),
        ),
    ]
