# Generated by Django 3.1.6 on 2021-02-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='View',
        ),
    ]
