# Generated by Django 3.1.6 on 2021-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210221_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='photo',
            name='view_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
